export { Home } from "./Home"
export { Dashboard } from "./Dashboard"
export { Login } from "./Login"
export { Profile } from "./Profile"
export { Signup } from "./Signup"
export { FedsView } from "./FedsView"